In [1]:
import numpy as np

In [10]:
vazio = np.empty([3,2], dtype=int)
vazio

array([[-1569570432,         552],
       [          0,           0],
       [          1,           0]])

In [12]:
zeros = np.zeros([3,2])
print(zeros)
diagonal = np.eye(5)
print(diagonal)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
k = np.array([[1,4,3],[4,5,6]])
print(k)
print(np.unique(k))

[[1 4 3]
 [4 5 6]]
[1 3 4 5 6]


In [16]:
#maximo
np.max(k)
print(np.max(k))
#minimo
print(np.min(k))
#media
np.mean(k)
#mediana
np.median(k)
#desvio padrao
np.std(k)
#variancia
np.var(k)


6
1


2.4722222222222228

In [18]:
print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [32]:
v = np.random.randn(4,4)
print(v)
x = (v>0)
print(x)
z = np.where(x)
print(z)
print(v[z])

[[-0.57837677 -0.92300881 -0.18895928  1.10607412]
 [-0.32377348 -0.24027479  0.32156616  0.7953741 ]
 [ 0.70256345  0.70436633  0.69818932 -0.57292859]
 [-1.75476319 -1.08021564 -1.77949064 -0.33265407]]
[[False False False  True]
 [False False  True  True]
 [ True  True  True False]
 [False False False False]]
(array([0, 1, 1, 2, 2, 2], dtype=int64), array([3, 2, 3, 0, 1, 2], dtype=int64))
[1.10607412 0.32156616 0.7953741  0.70256345 0.70436633 0.69818932]
